services:
  web:
<<<<<<< HEAD
    build:
      context: .
      dockerfile: Dockerfile
=======
    build: ./src
    ports:
      - "81:80"
>>>>>>> aa1993e (docker-compose.yml aldatuta)
    volumes:
      - ./src:/var/www/html
    environment:
      - ALLOW_OVERRIDE=true
    depends_on:
      - db

  db:
    image: mariadb:10.8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
    ports:
<<<<<<< HEAD
      - "8891:3306"
    volumes:
      - db_data:/var/lib/mysql
=======
      - "8889:3306"
    volumes:
      - ./mysql:/var/lib/mysql
>>>>>>> aa1993e (docker-compose.yml aldatuta)

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8890:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
<<<<<<< HEAD

  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  db_data:
=======
>>>>>>> aa1993e (docker-compose.yml aldatuta)
